#!C:/Program\ Files/Git/usr/bin/sh.exe
# shellcheck disable=SC2239

echo "Running lint check..."

# Lint check
./gradlew app:ktlintCheck --daemon

status=$?

# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0